/**
 * Mock Freelancers Data
 * 
 * Temporary mock data for development when backend API requires authentication.
 * This should be removed once proper authentication is implemented.
 */

import { Freelancer } from '../schema/discover-freelancers-data';

export const MOCK_FREELANCERS: Freelancer[] = [
  {
    id: '1',
    name: 'Maria Santos',
    title: 'Full Stack Web Developer',
    bio: 'Experienced full-stack developer specializing in React, Node.js, and PostgreSQL. I have 5+ years of experience building scalable web applications for startups and enterprises.',
    avatar: 'https://ui-avatars.com/api/?name=Maria+Santos&background=random',
    category: {
      id: 'web-dev',
      name: 'Web Development',
      slug: 'web-development',
    },
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Next.js'],
    hourlyRate: {
      min: 25,
      max: 40,
      currency: 'PHP',
    },
    experienceLevel: 'expert',
    rating: 4.9,
    reviewCount: 47,
    completedJobs: 89,
    successRate: 98,
    availability: 'available-now',
    location: 'Manila, Philippines',
    languages: ['English', 'Filipino'],
    isTopRated: true,
    isVerified: true,
    profileUrl: '/client/freelancers/1',
  },
  {
    id: '2',
    name: 'Juan Dela Cruz',
    title: 'Mobile App Developer',
    bio: 'iOS and Android developer with expertise in React Native and Flutter. Built 30+ mobile applications with over 1M downloads combined.',
    avatar: 'https://ui-avatars.com/api/?name=Juan+Dela+Cruz&background=random',
    category: {
      id: 'mobile-dev',
      name: 'Mobile Development',
      slug: 'mobile-development',
    },
    skills: ['React Native', 'Flutter', 'iOS', 'Android', 'Firebase'],
    hourlyRate: {
      min: 30,
      max: 45,
      currency: 'PHP',
    },
    experienceLevel: 'expert',
    rating: 4.8,
    reviewCount: 35,
    completedJobs: 67,
    successRate: 96,
    availability: 'available-1-week',
    location: 'Cebu City, Philippines',
    languages: ['English', 'Cebuano'],
    isTopRated: true,
    isVerified: true,
    profileUrl: '/client/freelancers/2',
  },
  {
    id: '3',
    name: 'Ana Reyes',
    title: 'UI/UX Designer',
    bio: 'Creative designer focused on user-centered design. Proficient in Figma, Adobe XD, and prototyping tools. Love creating beautiful and functional interfaces.',
    avatar: 'https://ui-avatars.com/api/?name=Ana+Reyes&background=random',
    category: {
      id: 'design',
      name: 'Design',
      slug: 'design',
    },
    skills: ['Figma', 'Adobe XD', 'UI Design', 'UX Research', 'Prototyping'],
    hourlyRate: {
      min: 20,
      max: 35,
      currency: 'PHP',
    },
    experienceLevel: 'intermediate',
    rating: 4.7,
    reviewCount: 28,
    completedJobs: 45,
    successRate: 94,
    availability: 'available-now',
    location: 'Davao City, Philippines',
    languages: ['English', 'Filipino'],
    isTopRated: false,
    isVerified: true,
    profileUrl: '/client/freelancers/3',
  },
  {
    id: '4',
    name: 'Carlos Mendoza',
    title: 'Backend Developer',
    bio: 'Backend specialist with strong experience in Node.js, Python, and microservices architecture. Passionate about building scalable and maintainable systems.',
    avatar: 'https://ui-avatars.com/api/?name=Carlos+Mendoza&background=random',
    category: {
      id: 'web-dev',
      name: 'Web Development',
      slug: 'web-development',
    },
    skills: ['Node.js', 'Python', 'PostgreSQL', 'MongoDB', 'Docker'],
    hourlyRate: {
      min: 28,
      max: 42,
      currency: 'PHP',
    },
    experienceLevel: 'expert',
    rating: 4.9,
    reviewCount: 52,
    completedJobs: 78,
    successRate: 97,
    availability: 'available-2-weeks',
    location: 'Quezon City, Philippines',
    languages: ['English', 'Spanish'],
    isTopRated: true,
    isVerified: true,
    profileUrl: '/client/freelancers/4',
  },
  {
    id: '5',
    name: 'Sofia Garcia',
    title: 'Content Writer',
    bio: 'Professional content writer and copywriter with 4 years of experience. Specializing in blog posts, website copy, and SEO content.',
    avatar: 'https://ui-avatars.com/api/?name=Sofia+Garcia&background=random',
    category: {
      id: 'writing',
      name: 'Writing & Translation',
      slug: 'writing-translation',
    },
    skills: ['Content Writing', 'Copywriting', 'SEO', 'Blog Writing', 'Proofreading'],
    hourlyRate: {
      min: 15,
      max: 25,
      currency: 'PHP',
    },
    experienceLevel: 'intermediate',
    rating: 4.6,
    reviewCount: 31,
    completedJobs: 56,
    successRate: 92,
    availability: 'available-now',
    location: 'Makati, Philippines',
    languages: ['English', 'Filipino'],
    isTopRated: false,
    isVerified: true,
    profileUrl: '/client/freelancers/5',
  },
  {
    id: '6',
    name: 'Miguel Torres',
    title: 'Data Analyst',
    bio: 'Data analyst with expertise in Python, SQL, and data visualization. Help businesses make data-driven decisions through insightful analysis.',
    avatar: 'https://ui-avatars.com/api/?name=Miguel+Torres&background=random',
    category: {
      id: 'data',
      name: 'Data Science',
      slug: 'data-science',
    },
    skills: ['Python', 'SQL', 'Tableau', 'Power BI', 'Excel'],
    hourlyRate: {
      min: 22,
      max: 35,
      currency: 'PHP',
    },
    experienceLevel: 'intermediate',
    rating: 4.5,
    reviewCount: 19,
    completedJobs: 34,
    successRate: 90,
    availability: 'available-1-week',
    location: 'Pasig City, Philippines',
    languages: ['English', 'Filipino'],
    isTopRated: false,
    isVerified: false,
    profileUrl: '/client/freelancers/6',
  },
];
